### ISSUE TITLE
Errors working with develop and magento 2.4.2-p1

### ISSUE THREAD

**Issue by jdigiorgio** [DivanteLtd/magento2-pimcore-bridge#46]
I am trying to work with the develop branch here and the develop-v2 branch on the pimcore side. Per the readme, I copied the files in the repo to <root>/app/code/Divante/PimcoreIntegration. Once that is done, if I try to run setup:di:compile I get the following error:

`
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 17 secs 414.0 MiBErrors during compilation:
	Divante\PimcoreIntegration\Model\CategoryRepository
		Missed required argument populateWithValues in parent::__construct call. File: /var/www/html/app/code/Divante/PimcoreIntegration/Model/CategoryRepository.php
`

Also I get this error in bridge_critical.log after running bin/magento divante:queue-category:process with some categories in the queue:

`
StreamLogger.CRITICAL: Type Error occurred when creating object: Divante\PimcoreIntegration\Model\CategoryRepository\Interceptor, Too few arguments to function Magento\Catalog\Model\CategoryRepository::__construct(), 3 passed in /var/www/html/app/code/Divante/PimcoreIntegration/Model/CategoryRepository.php on line 43 and exactly 4 expected [] []
`

I don't know for sure that these are related, I just noted that they are referencing the same file and I think the same function call.
